return {
    version = "0.1.0",
    cleaner = require("./flightFramework/cleaner"),
    leader = require("./flightFramework/leader"),
    lifecycle = require("./flightFramework/lifecycle"),
    motion = require("./flightFramework/motion"),
    network = require("./flightFramework/network"),
    players = require("./flightFramework/players"),
    scheduler = require("./flightFramework/scheduler"),
    schemas = require("./flightFramework/schemas"),
    signal = require("./flightFramework/signal"),
    state = require("./flightFramework/state"),
    utils = require("./flightFramework/utils"),
}